only: issues
staleLabel: stale
daysUntilStale: 90
daysUntilClose: 14

markComment: >
  This issue has been marked as stale because due to inactivity.
  It will be closed in 14 days if no further activity occurs.
